const RESPONSE_CODE = {
  SUCCESS_QUERY: 200,
  SUCCESS_MUTATION: 201,
  NOT_FOUND: 404,
  INVALID_INPUT: 400,
  UNAUTHORIZED: 401,
  TOKEN_EXPIRED: 403,
  SERVER_ERROR: 500,
};

module.exports = {
  RESPONSE_CODE,
};

